# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a69527ae0eb212c6f2ad784dfe10d63c2ebc410129f1d78212f0a0152b7d52c7d981b13a4e1a60d24353d411f7677845ed0c340c43e8f240e15fcac4fb03ff5

test:
  secret_key_base: 00887b68227261ca8e544a102adddcbef406e530fddbf45b3756ac6669cf41a0a6aac8d88ddc615f0e51b9308c8f83d03c313da8f6e7ad51871bcb412a1cb643

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
